// This file is auto-generated by scripts/upload-assets.mjs
// Do not edit manually
const assetMap: Record<string, string> = {
  "/videos/FONDO-WEB-16-9.mp4": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/videos/FONDO-WEB-16-9-0wdF4rZr6bS7QBMKo8dvIgPW4MSJvp.mp4",
  "/images/encuentro-2025/GIS06445.JPG": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/encuentro-2025/GIS06445-teGsjPSWXJ3CAPNp4pcspqhldesD9K.JPG",
  "/images/encuentro-2025/GIS06446.JPG": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/encuentro-2025/GIS06446-x50bHpObrYbbX0MC6JmqlDefJ6NGIZ.JPG",
  "/images/encuentro-2025/GIS06447.JPG": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/encuentro-2025/GIS06447-GIxk5QCGkxCuiBaRUySukfnqVtwfwI.JPG",
  "/images/encuentro-2025/GIS06449.JPG": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/encuentro-2025/GIS06449-Cp0CGPvTLpHX1T0LWT8ZGMtgnPegOv.JPG",
  "/images/eventos/20241112_092951.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/20241112_092951-a6JTfoTGl16I0uYyvv6VVlwfNQ9Nwb.jpg",
  "/images/eventos/20241112_100049.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/20241112_100049-4WeZ4K27j0DYNx7K3uKnCBPM02A8Jf.jpg",
  "/images/eventos/20241112_102515.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/20241112_102515-h1SGW68NNRyIzlCjC5ZqioJswIwncT.jpg",
  "/images/eventos/20241112_092855.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/20241112_092855-HqgXn1xze0ANi2mTfFQ1yrGrrt9E2o.jpg",
  "/images/eventos/20241112_095957.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/20241112_095957-t4TcYlBDO9GNFCImRjgBUrwkbXZpVQ.jpg",
  "/images/eventos/20241112_100147.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/20241112_100147-3MljfsZzdAOTRCXMtjaHN1rvaCPYJj.jpg",
  "/images/eventos/20241112_111016.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/20241112_111016-VnmRxYxmQcl0gXNnPxDx8isXoXQr8V.jpg",
  "/images/eventos/GIS08397.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/GIS08397-a4GxDZuaqrspKhvvAF7rUROYH2Nd4u.jpg",
  "/images/eventos/20241112_111009.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/20241112_111009-biumt26D4RSjcBiTBJv54i3eJkvElE.jpg",
  "/images/eventos/20241112_102357.jpg": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/eventos/20241112_102357-bEyiQYBlCYA6UKjZAc1LlVb31xxhDh.jpg",
  "/images/equipo-shoot/GIS08548.JPG": "https://klfmgyd7vurvk9nb.private.blob.vercel-storage.com/images/equipo-shoot/GIS08548-nUmDUNolgAf5oMgG6wuftFGbWpSfJp.JPG",
};
export default assetMap;
