// This file is auto-generated by scripts/upload-assets.mjs
// Do not edit manually
const assetMap: Record<string, string> = {
  "/videos/FONDO-WEB-16-9.mp4": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/videos/FONDO-WEB-16-9-j0i0hYWjL43H7NJ9q7pA4H6qCUjVEh.mp4",
  "/images/encuentro-2025/GIS06445.JPG": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/encuentro-2025/GIS06445-pdLMmr3nBUTZcl38iM6DtzuD2Pv1Yf.JPG",
  "/images/encuentro-2025/GIS06446.JPG": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/encuentro-2025/GIS06446-rfm4mbrWBL7hKzWing4bQa3ylwvyYP.JPG",
  "/images/encuentro-2025/GIS06447.JPG": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/encuentro-2025/GIS06447-A1AKngfooCVHVcFX9wLOAD3QvTde6Q.JPG",
  "/images/encuentro-2025/GIS06449.JPG": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/encuentro-2025/GIS06449-55r995h4PI4po3sJhCxWLx9Ygh8aMb.JPG",
  "/images/eventos/20241112_092951.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/20241112_092951-tup74bYR18kLQ6TFzgY0wNeDZRk6w1.jpg",
  "/images/eventos/20241112_100049.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/20241112_100049-mBWZkjmqDLtBSI3kcFHZebuCxNVW1A.jpg",
  "/images/eventos/20241112_102515.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/20241112_102515-dQlUNy16HzxhV28YqvF88Tc8fDjVcH.jpg",
  "/images/eventos/20241112_092855.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/20241112_092855-9SZZe4IC2hKAFGiW0qr1TKrM2f45KZ.jpg",
  "/images/eventos/20241112_095957.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/20241112_095957-qhr9J75nx7PlwGn5XRoURKIQuFc5nP.jpg",
  "/images/eventos/20241112_100147.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/20241112_100147-0uuJ2qgDT2OBCBL6ZeXMVJ8oPCVb2e.jpg",
  "/images/eventos/20241112_111016.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/20241112_111016-TCsfgfVtkTJb2OXRc09KlIjdqPhfFl.jpg",
  "/images/eventos/GIS08397.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/GIS08397-ADchlavVvIXAsHUGiWaZ82Im9roa4l.jpg",
  "/images/eventos/20241112_111009.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/20241112_111009-i0SMBGlNcSemeELdQWUETgS3OmH6iB.jpg",
  "/images/eventos/20241112_102357.jpg": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/eventos/20241112_102357-oRTff1ej1ciZwYIlSBi8gysLVCueCr.jpg",
  "/images/equipo-shoot/GIS08548.JPG": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/images/equipo-shoot/GIS08548-tgfhW5OOmtudMQsDEApdqR3lEGdHMp.JPG",
};
export default assetMap;
