// This file is auto-generated by scripts/upload-assets.mjs
// Do not edit manually
const assetMap: Record<string, string> = {
  "/documents/2.Informe-de-Gestion-2024-ASCEP_Maicol-Londono.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/2.Informe-de-Gestion-2024-ASCEP_Maicol-Londono-MnBMYhpKPKpEPfzQhUfQeEifykYHrn.pdf",
  "/documents/1.Registro_Web_2024.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/1.Registro_Web_2024-icAl5OBCqHW3LBtW3kyPZCHKW0SJuJ.pdf",
  "/documents/1.Registro_WEB_2025.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/1.Registro_WEB_2025-LbcvawrZnF3lsoHvhG41b1tAStkYbd.pdf",
  "/documents/3.Estados_Financieros_2023_ASCEP.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/3.Estados_Financieros_2023_ASCEP-uYFAI60vlF0NQOOY8YCz3PXOtiE9d1.pdf",
  "/documents/2.Informe_de_Gestion_2023.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/2.Informe_de_Gestion_2023-nghOScAIe771JU4w605e9Mu8LNqmA7.pdf",
  "/documents/6.Certificado_requisitos.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/6.Certificado_requisitos-91ZJNC56d1QARWBTDWmcUG45TrUvsS.pdf",
  "/documents/5.Declaracion_Renta_2023.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/5.Declaracion_Renta_2023-kt41eWoR4DEUMj5mpil13SfBqcQa64.pdf",
  "/documents/7.Certificado_cargos_directivos-y-gerenciales.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/7.Certificado_cargos_directivos-y-gerenciales-hxRgMGxsq5gQ83S1tXJwmfdfxCnxpM.pdf",
  "/documents/4.RUT_ASCEP.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/4.RUT_ASCEP-oQLRW7h0qqsWv48e1lCGdOFvvoskVj.pdf",
  "/documents/3.Estados-Financieros-2024_ASCEP_firmados.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/3.Estados-Financieros-2024_ASCEP_firmados-zlbvWZMvMfPXatYXuGK4qTi6lEzCZu.pdf",
  "/documents/9.Formato_2530_2531.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/9.Formato_2530_2531-MitJmCgXPpbaNNACs0TOn5RiLjd4cx.pdf",
  "/documents/Presentacion.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/Presentacion-BmyC9TpuzLV2vCJWvumFOXBFn467tF.pdf",
  "/documents/8.Certificado_antecedentes_judiciales.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/8.Certificado_antecedentes_judiciales-Zw1OPMQtFJRGx2NyeEaOCcOinsCn5a.pdf",
  "/documents/DOCUMENTO BASE ASOCIACIÓN.docx.pdf": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/documents/DOCUMENTO%20BASE%20ASOCIACI%C3%93N.docx.pdf",
  "/videos/FONDO-WEB-16-9.mp4": "https://rxt2dhtgckbkb1oj.public.blob.vercel-storage.com/videos/FONDO-WEB-16-9.mp4",
};
export default assetMap;
